### ISSUE TITLE
Problem with scaling with region decoding

### ISSUE THREAD

**Issue by SammyVimes** [suckgamony/RapidDecoder#2]
Say I have 690*10700 image. I want to show it's top part (0;0) - (690;1200). I have variable "regional" in executeDecoding method of BitmapLoader set to false. But it is obviously wrong.

**Comment by ganeshdroid** [comment]
I'm using this library to get a bitmap from Inputstream.
I'm using the below lines:
decoder = BitmapDecoder.from(content.getPanelNav().getImageStream(index)).scaleBy(0.5f);
                        bitmap = decoder
                                .scale(getDeviceWidth(), getDeviceHeight())
                                .useBuiltInDecoder(true)
                                .decode();
It is always giving "OutOfMemoryError", even if the image is in large size(6 MB)or small size(1-3MB).
Can you please suggest me what is the issue here.

**Comment by danielgomezrico** [comment]
Any updates from this?
